env: dev
pullPolicy: IfNotPresent
project-name: "Dev-Project"

ingress:
  enabled: false
  className: "webapprouting.kubernetes.azure.com"
  annotations:
    kubernetes.io/ingress.class: "addon-http-application-routing"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
  hosts:
    - host: dev.information-guide.com
      paths:
        - path: /
          pathType: Prefix
          backend_service: information-guide-web
          port: 3000
        - path: /api
          pathType: Prefix
          backend_service: information-guide-service
          port: 3000
  tls:
    - secretName: ingress-cert-secret
      hosts:
        - dev.information-guide.com

apps:
  - name: information-guide-web
    repository: "us-central1-docker.pkg.dev/dev-project-490411/myartifactregistry/gcp-test"
    tag: "9ae1a9226cf43c113706ce947152caf487fc43c0"
    hpa:
      enabled: false
      maxReplicas: 2
      minReplicas: 1
      resourceName: cpu
      resourceType: Utilization
      resourceValue: 70
    pvc: {}
    resources: 
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits: 
        memory: "100Mi"
        cpu: "100m"
    startupProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 45
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 45
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 45
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3
    ports: 
      - containerPort: 80
        protocol: TCP 
    secrets:
      enabled: false
      secrets: # Renamed from 'secrets' to avoid confusion
        db: ""
    #variables: 
     # Backend_service: "http://information-guide-service:3000"

  - name: information-guide-service
    repository: "us-central1-docker.pkg.dev/dev-project-490411/myartifactregistry/gcp-test"
    tag: "9ae1a9226cf43c113706ce947152caf487fc43c0"
    hpa:
      enabled: false
      maxReplicas: 2
      minReplicas: 1
      resourceName: cpu
      resourceType: Utilization
      resourceValue: 70
    pvc: {}
    resources: 
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits: 
        memory: "100Mi"
        cpu: "100m"
    ports: 
      - containerPort: 80
        protocol: TCP
    secrets:
      enabled: false
      secrets:
        db: ""
    variables: {} # Ensure this is an empty map, not null

#########################################################################################

services:
  - service_name: information-guide-web
    type: ClusterIP
    annotations: {}
    ports:
      - protocol: TCP
        name: http
        port: 80
        targetPort: 80

  - service_name: information-guide-service
    type: ClusterIP
    annotations: {}
    ports:
      - protocol: TCP
        name: http
        port: 80

        targetPort: 80

