env: dev
pullPolicy: IfNotPresent
project-name: "Dev-Project"
gateway:
  enabled: true
  name: sample-gateway
  certificate_map_name: sample-gateway-api-cert-map
  host: dev.sample.com
  tls_secret_name: sample-tls-secret
apps:
  - name: information-guide-web
    repository: "us-central1-docker.pkg.dev/dev-project-490411/myartifactregistry/gcp-test"
    tag: "2f3ac35"
    hpa:
      enabled: false
      maxReplicas: 2
      minReplicas: 1
      resourceName: cpu
      resourceType: Utilization
      resourceValue: 70
    pvc: {}
    resources:
      requests:
        memory: "20Mi"
        cpu: "20m"
      limits:
        memory: "50Mi"
        cpu: "50m"
    startupProbe:
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 45
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 45
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 45
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3
    ports:
      - containerPort: 3000
        protocol: TCP
    secrets:
      enabled: false
      secrets: # Renamed from 'secrets' to avoid confusion
        db: ""
        #variables: 
  - name: information-guide-service
    # Backend_service: "http://information-guide-service:3000"

    repository: "us-central1-docker.pkg.dev/dev-project-490411/myartifactregistry/gcp-test"
    tag: "2f3ac35"
    hpa:
      enabled: false
      maxReplicas: 2
      minReplicas: 1
      resourceName: cpu
      resourceType: Utilization
      resourceValue: 70
    pvc: {}
    resources:
      requests:
        memory: "20Mi"
        cpu: "20m"
      limits:
        memory: "50Mi"
        cpu: "50m"
    ports:
      - containerPort: 3000
        protocol: TCP
    secrets:
      enabled: false
      secrets:
        db: ""
    variables: {} # Ensure this is an empty map, not null
#########################################################################################
services:
  # - service_name: information-guide-web
  #   type: ClusterIP
  #   annotations: {}
  #   ports:
  #     - protocol: TCP
  #       name: http
  #       port: 3000
  #       targetPort: 3000
  - service_name: information-guide-service
    type: ClusterIP
    annotations: {}
    ports:
      - protocol: TCP
        name: http
        port: 3000
        targetPort: 3000
  - service_name: information-guide-web
    type: ClusterIP
    annotations: {}
    ports:
      - protocol: TCP
        name: http
        port: 3000
        targetPort: 3000
    gw_http_route:
      enabled: true
      matchRules:
        - path: /
          backend:
            name: information-guide-web
            port: 3000
      backend_policy:
        enabled: true
        securityPolicy:
          policyName: sample-cloudflare-waf
        iap:
          enabled: true
          secret_name: sample-secret-iap
          client_id: 946678058338-mep26vp89n99va6fol1ovhccvr6ep8e4.apps.googleusercontent.com
        logging:
          enabled: true
      healthCheckPolicy:
        enabled: true
        checkIntervalSec: 3
        timeoutSec: 2
        healthyThreshold: 1
        unhealthyThreshold: 3
        requestPath: /
      selfManaged:
        enabled: false
        domainName: dev.sample.com
        secretName: sample-selfmanaged-secret
        keyName: sample_key
        pem: ""
