{{- $service0 := index .Values.services 0 | default dict -}}
{{- $gw := $service0.gw_http_route | default dict -}}
{{- $hosts := $gw.hosts | default list -}}

{{- $host := "" -}}
{{- if gt (len $hosts) 0 -}}
  {{- $host = (index $hosts 0).domainName | default "" -}}
{{- end -}}

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gw.gateway_name | default "default-gateway" }}

spec:
  gatewayClassName: gke-l7-global-external-managed

  listeners:
    - name: https
      protocol: HTTPS
      port: 443

      {{- if $host }}
      hostname: {{ $host }}
      {{- end }}

      tls:
        mode: Terminate
        options:
          {{- if $gw.certificate_map_name }}
          networking.gke.io/certmap: {{ $gw.certificate_map_name }}
          {{- end }}