{{- $gw := .Values.gateway | default dict -}}

{{- if $gw.enabled }}

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gw.name }}
  {{- if $gw.certificate_map_name }}
  annotations:
    networking.gke.io/certmap: {{ $gw.certificate_map_name }}
  {{- end }}

spec:
  gatewayClassName: gke-l7-global-external-managed

  listeners:
    - name: https
      protocol: HTTPS
      port: 443

      {{- if $gw.host }}
      hostname: {{ $gw.host }}
      {{- end }}

      tls:
        mode: Terminate

{{- end }}