{{- range .Values.services }}
{{- $gw := .gw_http_route | default dict }}
{{- $bp := $gw.backend_policy | default dict }}
{{- $hc := $gw.healthCheckPolicy | default dict }}

{{- if $bp.enabled }}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .service_name }}-bc

spec:
  healthCheck:
    checkIntervalSec: {{ $hc.checkIntervalSec }}
    timeoutSec: {{ $hc.timeoutSec }}
    healthyThreshold: {{ $hc.healthyThreshold }}
    unhealthyThreshold: {{ $hc.unhealthyThreshold }}
    type: HTTP
    requestPath: {{ $hc.requestPath }}

  securityPolicy:
    name: {{ $bp.securityPolicy.policyName }}

  logging:
    enable: {{ $bp.logging.enabled }}

  iap:
    enabled: {{ $bp.iap.enabled }}
    oauthclientCredentials:
      secretName: {{ $bp.iap.secret_name }}
{{- end }}
{{- end }}