{{- range .Values.services }}

{{- if and .gw_http_route .gw_http_route.backend_policy (default false .gw_http_route.backend_policy.enabled) }}

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .service_name }}-bc

spec:
  securityPolicy:
    name: {{ .gw_http_route.backend_policy.securityPolicy.policyName }}

  iap:
    enabled: {{ .gw_http_route.backend_policy.iap.enabled }}
    oauthclientCredentials:
      secretName: {{ .gw_http_route.backend_policy.iap.secret_name }}

  logging:
    enable: {{ .gw_http_route.backend_policy.logging.enabled }}

{{- end }}

{{- end }}