{{- if .Values.gw_http_route.selfManaged.enabled }}
apiVersion: networking.gke.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gw_http_route.gateway_name }}
spec:
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.gw_http_route.selfManaged.secretName }}
{{- end }}