{{- range .Values.services }}
{{- $gw := .gw_http_route | default dict }}
{{- $hc := $gw.healthCheckPolicy | default dict }}

{{- if $hc.enabled }}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .service_name }}-hc

spec:
  default:
    checkIntervalSec: {{ $hc.checkIntervalSec }}
    timeoutSec: {{ $hc.timeoutSec }}
    healthyThreshold: {{ $hc.healthyThreshold }}
    unhealthyThreshold: {{ $hc.unhealthyThreshold }}

    config:
      type: HTTP
      httpHealthCheck:
        requestPath: {{ $hc.requestPath }}
{{- end }}
{{- end }}