{{- range .Values.apps }}
{{- if .secrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: my-keyvault-4732
    kind: SecretStore
  target:
    name: {{ .name }}-secret
    creationPolicy: Owner
  data:
    {{- range .externalSecrets.secrets }}
    - secretKey: {{ .k8sSecretKey }}
      remoteRef:
        key: {{ .keyVaultSecretName }}
    {{- end }}
{{- end }}

{{- end }}


