{{- range .Values.apps }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  annotations:
    # Example for Azure Workload Identity / AWS IRSA
    azure.workload.identity/client-id: "your-sp-client-id"
---
{{- end }}