name: Build and push the docker image 

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/946678058338/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-sa@dev-project-490411.iam.gserviceaccount.com

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
   
    - name: Set short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build Image
      run: |
        docker build -t us-central1-docker.pkg.dev/dev-project-490411/myartifactregistry/gcp-test:${SHORT_SHA}  .

    - name: Push Image
      run: |
        docker push us-central1-docker.pkg.dev/dev-project-490411/myartifactregistry/gcp-test:${SHORT_SHA}
