name: Depploy to GKE using Helm
on:
  workflow_run:
    workflows: ["Build and push the docker image"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - qa

jobs:
  deploy:
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write   # Required for OIDC

    env:
      ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract short SHA
      run: echo "SHORT_SHA=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq

    - name: Set SHORT_SHA (auto from CI)
      if: ${{ github.event_name == 'workflow_run' }}
      run: echo "SHORT_SHA=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Set SHORT_SHA (manual input or fallback)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        if [ -n "${{ github.event.inputs.image_tag }}" ]; then
          echo "SHORT_SHA=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
        else
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        fi

    - name: Update values file
      run: |
        yq -i '.apps[].tag = env(SHORT_SHA)' values.${ENV}.yaml

    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add values.${ENV}.yaml
        git commit -m "chore(${ENV}): deploy ${SHORT_SHA}" || echo "No changes"
        git push

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/946678058338/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-sa@dev-project-490411.iam.gserviceaccount.com

    - name: setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Install GKE auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: get gke credentails
      run: |
        gcloud container clusters get-credentials my-gke-cluster --region us-central1 --project dev-project-490411

    - name: install helm
      uses: azure/setup-helm@v4

    - name: deploy helm
      run: |
        helm upgrade --install my-app ./multiple-service-base-chart \
          -f values.${ENV}.yaml \
          --set apps[0].tag=${SHORT_SHA},apps[1].tag=${SHORT_SHA} \
          --namespace ${ENV} \
          --create-namespace

        
