name: Depploy to GKE using Helm
on:
  workflow_run:
    workflows: ["Build and push the docker image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write   # Required for OIDC

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract short SHA
      run: echo "SHORT_SHA=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq

    - name: Update values.yaml
      run: |
        yq -i '.apps[].tag = env(SHORT_SHA)' values.dev.yaml

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add values.dev.yaml
        git commit -m "chore: update image tag to ${SHORT_SHA}" || echo "No changes"
        git push

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/946678058338/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-sa@dev-project-490411.iam.gserviceaccount.com

    - name: setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Install GKE auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: get gke credentails
      run: |
        gcloud container clusters get-credentials my-gke-cluster --region us-central1 --project dev-project-490411

    - name: install helm
      uses: azure/setup-helm@v4

    - name: deploy helm
      run: |
        helm upgrade --install my-app ./multiple-service-base-chart \
          -f values.dev.yaml \
          --set apps[0].tag=${SHORT_SHA},apps[1].tag=${SHORT_SHA} \
          --namespace dev \
          --create-namespace

        
